version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client/src:/app/src # Links the source files to the running container
    ports:
      - "3000:8000"